server:
  port: 8080

spring:
  application:
    name: fitness-auth-skeleton
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fit_recom_sys?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 456852sa

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.fitness.system.entity,com.example.fitness.auth.vo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  jwt:
    secret: ReplaceThisWithAtLeast32BytesSecretKey1234567890
    expire-millis: 72000000
